version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:2.7.14

jobs:
  build:
    executor: python
    steps:
      - run:
          name: install c7n
          command: pip install --user c7n
      - run:
          name: custodian version
          command: /home/circleci/.local/bin/custodian version
      - run:
          name: validate policies
          command: |
            cd $CIRCLE_WORKING_DIRECTORY/policies
            /home/circleci/.local/bin/custodian validate
