version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:2.7.14

jobs:
  build:
    executor: python
    steps:
      - run:
          name: install c7n
          command: pip install --user c7n
      - run: custodian -h
